---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
spec:
  type: NodePort
  selector:
    app: etcd-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-app
  labels:
    app: etcd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd-app
  template:
    metadata:
      labels:
        app: etcd-app
    spec:
      containers:
        - name: etcd-app
          image: jiayan/etcdapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: "etcdURL"
            value: "http://etcd-client.default.svc.cluster.local:2379"